-- =============================================
-- Proceso: Proyectos/Ins_Proyecto
-- =============================================
--START_PARAM
set 
    @nombre = '',
    @direccion = '',
    @id_sede = 0,
    @id_zona_proyecto = 0,
    @id_ciudadela = 0,
    @id_tipo_proyecto = 0,
    @otra_info = '',
    @id_estado_publicacion = 0,

    @subsidios_vis = '',
    @dias_separacion = '',
    @dias_cierre_sala = '',
    @meses_ci = '',
    @dias_pago_ci_banco_amigo = '',
    @dias_pago_ci_banco_no_amigo = '',
    @email_cotizaciones = '',
    @meta_ventas = '',
    @id_pie_legal = 0,
    @id_banco_constructor = 0,
    @id_tipo_financiacion = 0,
    @id_tipo_vis = 0,

    @centro_costos = '',
    @id_fiduciaria = 0,
    @id_opcion_visual = 0,

    @lanzamiento = '',
    @ciudad_lanzamiento = '',
    @fecha_lanzamiento = '',
    @latitud = '',
    @bloqueo_libres = '',
    @inmuebles_opcionados = '',
    @tipos_excluidos = '',
    @link_waze = '',
    @linea_whatsapp = '',

    @email_receptor_1 = '',
    @email_receptor_2 = '',
    @email_receptor_3 = '',
    @email_receptor_4 = '',

    @link_general_onelink = '',
    @link_especifico_onelink = '',
    @incluir_especificaciones_tecnicias = '',
    @link_especificaciones_tecnicias = '',
    @incluir_cartilla_negocios_cotizacion = '',
    @incluir_cartilla_negocios_opcion = '',
    @link_cartilla_negocios = '',
    @frame_seguimiento_visible = '',
    @link_seguimiento_leads = '',
    @frame_evaluacion_conocimiento = '',
    @link_evaluacion_conocimiento = '',
    @avance_obra_visible = '',
    @link_avance_obra = '',
    @incluir_brochure = '',
    @link_brochure = '';
--END_PARAM

insert into fact_proyectos (
    nombre,
    direccion,
    id_sede,
    id_zona_proyecto,
    id_ciudadela,
    id_tipo_proyecto,
    otra_info,
    id_estado_publicacion,

    subsidios_vis,
    dias_separacion,
    dias_cierre_sala,
    meses_ci,
    dias_pago_ci_banco_amigo,
    dias_pago_ci_banco_no_amigo,
    email_cotizaciones,
    meta_ventas,
    id_pie_legal,
    id_banco_constructor,
    id_tipo_financiacion,
    id_tipo_vis,

    centro_costos,
    id_fiduciaria,
    id_opcion_visual,

    lanzamiento,
    ciudad_lanzamiento,
    fecha_lanzamiento,
    latitud,
    bloqueo_libres,
    inmuebles_opcionados,
    tipos_excluidos,
    link_waze,
    linea_whatsapp,

    email_receptor_1,
    email_receptor_2,
    email_receptor_3,
    email_receptor_4,

    link_general_onelink,
    link_especifico_onelink,
    incluir_especificaciones_tecnicias,
    link_especificaciones_tecnicias,
    incluir_cartilla_negocios_cotizacion,
    incluir_cartilla_negocios_opcion,
    link_cartilla_negocios,
    frame_seguimiento_visible,
    link_seguimiento_leads,
    frame_evaluacion_conocimiento,
    link_evaluacion_conocimiento,
    avance_obra_visible,
    link_avance_obra,
    incluir_brochure,
    link_brochure
)
select 
    @nombre,
    @direccion,
    nullif(@id_sede, 0),
    nullif(@id_zona_proyecto, 0),
    nullif(@id_ciudadela, 0),
    nullif(@id_tipo_proyecto, 0),
    @otra_info,
    nullif(@id_estado_publicacion, 0),

    @subsidios_vis,
    @dias_separacion,
    @dias_cierre_sala,
    @meses_ci,
    @dias_pago_ci_banco_amigo,
    @dias_pago_ci_banco_no_amigo,
    @email_cotizaciones,
    @meta_ventas,
    nullif(@id_pie_legal, 0),
    nullif(@id_banco_constructor, 0),
    nullif(@id_tipo_financiacion, 0),
    nullif(@id_tipo_vis, 0),

    @centro_costos,
    nullif(@id_fiduciaria, 0),
    nullif(@id_opcion_visual, 0),

    @lanzamiento,
    @ciudad_lanzamiento,
    @fecha_lanzamiento,
    @latitud,
    @bloqueo_libres,
    @inmuebles_opcionados,
    @tipos_excluidos,
    @link_waze,
    @linea_whatsapp,

    @email_receptor_1,
    @email_receptor_2,
    @email_receptor_3,
    @email_receptor_4,

    @link_general_onelink,
    @link_especifico_onelink,
    @incluir_especificaciones_tecnicias,
    @link_especificaciones_tecnicias,
    @incluir_cartilla_negocios_cotizacion,
    @incluir_cartilla_negocios_opcion,
    @link_cartilla_negocios,
    @frame_seguimiento_visible,
    @link_seguimiento_leads,
    @frame_evaluacion_conocimiento,
    @link_evaluacion_conocimiento,
    @avance_obra_visible,
    @link_avance_obra,
    @incluir_brochure,
    @link_brochure;

select 'OK' as resp;
