-- =============================================
-- Proceso: ProcesoNegocio/Ins_Opcion
-- =============================================
--START_PARAM
set @id_cotizacion = '1',
    @fecha_entrega = '2030-05-17',
    @created_by = 'alejandros',
    @valor_reformas = '0',
    @valor_acabados = '0',
    @valor_descuento_adicional = '0',
    @valor_separacion = '6600000',
    @valor_escrituras = '0',
    @notariales = '0',
    @beneficiencia = '0',
    @registro = '0',
    @pago_contado = '0',
    @pago_financiado = '1',
    @id_entidad = NULL,
    @id_tipo = NULL,
    @id_anios = NULL,
    @id_modalidad = NULL,
    @subsidio_activo = '0',
    @ingresos_familiares = '0',
    @cesantias = '0',
    @ahorros = '0',
    @fin_max_permisible = '0',
    @cuota_permisible = '0',
    @cuota_max_financiable = '0',
    @ingr_regs_max = '0',
    @anio_entrega = NULL,
    @valor_subsidio = '0',
    @id_caja_compensacion = NULL,
    @meses = '0',
    @importe_financiacion = '0',
    @cuota_inicial = '0',
    @fecha_primera_cuota = NULL,
    @fecha_ultima_cuota = NULL,
    @fecha_escrituracion = NULL;
--END_PARAM

insert into fact_opcion (
    id_cotizacion,
    fecha_entrega,
    valor_reformas,
    valor_acabados,
    valor_descuento_adicional,
    valor_separacion,
    valor_escrituras,
    notariales,
    beneficiencia,
    registro,
    pago_contado,
    pago_financiado,
    id_entidad,
    id_tipo,
    id_anios,
    id_modalidad,
    subsidio_activo,
    ingresos_familiares,
    cesantias,
    ahorros,
    fin_max_permisible,
    cuota_permisible,
    cuota_max_financiable,
    ingr_regs_max,
    anio_entrega,
    valor_subsidio,
    id_caja_compensacion,
    meses,
    importe_financiacion,
    cuota_inicial,
    fecha_primera_cuota,
    fecha_ultima_cuota,
    fecha_escrituracion,
    created_by
) values (
    @id_cotizacion,
    @fecha_entrega,
    @valor_reformas,
    @valor_acabados,
    @valor_descuento_adicional,
    @valor_separacion,
    @valor_escrituras,
    @notariales,
    @beneficiencia,
    @registro,
    @pago_contado,
    @pago_financiado,
    @id_entidad,
    @id_tipo,
    @id_anios,
    @id_modalidad,
    @subsidio_activo,
    @ingresos_familiares,
    @cesantias,
    @ahorros,
    @fin_max_permisible,
    @cuota_permisible,
    @cuota_max_financiable,
    @ingr_regs_max,
    @anio_entrega,
    @valor_subsidio,
    @id_caja_compensacion,
    @meses,
    @importe_financiacion,
    @cuota_inicial,
    @fecha_primera_cuota,
    @fecha_ultima_cuota,
    @fecha_escrituracion,
    @created_by
);

select concat('ok-id_opcion:', last_insert_id()) as result;
