-- =============================================
-- Proceso: ProcesoNegocio/Upd_Opcion
-- =============================================
--START_PARAM
set @id_opcion = '1',
    @fecha_entrega = '2030-05-17',
    @valor_reformas = '0',
    @valor_acabados = '0',
    @valor_descuento_adicional = '0',
    @valor_separacion = '6600000',
    @valor_escrituras = '0',
    @notariales = '0',
    @beneficiencia = '0',
    @registro = '0',
    @pago_contado = '0',
    @pago_financiado = '1',
    @id_entidad = NULL,
    @id_tipo = NULL,
    @id_anios = NULL,
    @id_modalidad = NULL,
    @subsidio_activo = '0',
    @ingresos_familiares = '0',
    @cesantias = '0',
    @ahorros = '0',
    @fin_max_permisible = '0',
    @cuota_permisible = '0',
    @cuota_max_financiable = '0',
    @ingr_regs_max = '0',
    @anio_entrega = NULL,
    @valor_subsidio = '0',
    @id_caja_compensacion = NULL,
    @meses = '0',
    @importe_financiacion = '0',
    @cuota_inicial = '0',
    @fecha_primera_cuota = NULL,
    @fecha_ultima_cuota = NULL,
    @fecha_escrituracion = NULL,
    @id_banco_factor = NULL,
    @id_pie_legal = NULL;
--END_PARAM

update fact_opcion
set
    fecha_entrega = @fecha_entrega,
    valor_reformas = @valor_reformas,
    valor_acabados = @valor_acabados,
    valor_descuento_adicional = @valor_descuento_adicional,
    valor_separacion = @valor_separacion,
    valor_escrituras = @valor_escrituras,
    notariales = @notariales,
    beneficiencia = @beneficiencia,
    registro = @registro,
    pago_contado = @pago_contado,
    pago_financiado = @pago_financiado,
    id_entidad = @id_entidad,
    id_tipo = @id_tipo,
    id_anios = @id_anios,
    id_modalidad = @id_modalidad,
    subsidio_activo = @subsidio_activo,
    ingresos_familiares = @ingresos_familiares,
    cesantias = @cesantias,
    ahorros = @ahorros,
    fin_max_permisible = @fin_max_permisible,
    cuota_permisible = @cuota_permisible,
    cuota_max_financiable = @cuota_max_financiable,
    ingr_regs_max = @ingr_regs_max,
    anio_entrega = @anio_entrega,
    valor_subsidio = @valor_subsidio,
    id_caja_compensacion = @id_caja_compensacion,
    meses = @meses,
    importe_financiacion = @importe_financiacion,
    cuota_inicial = @cuota_inicial,
    fecha_primera_cuota = @fecha_primera_cuota,
    fecha_ultima_cuota = @fecha_ultima_cuota,
    fecha_escrituracion = @fecha_escrituracion,
    id_banco_factor = if(@id_banco_factor = '', null, @id_banco_factor),
    id_pie_legal = if(@id_pie_legal = '', null, @id_pie_legal)
where id_opcion = @id_opcion;

select concat('ok-id_opcion:', @id_opcion, ' ', 'updated') as result;
